sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t chetannarang123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chetannarang123/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Elastcid-beanstalk-demo"
  env: "Elastcid-beanstalk-demo-env"
  bucket_name: "elasticbeanstalk-us-east-1-228492377945"
  bucket_path: "Elastcid-beanstalk-demo"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
